# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e24baf1389eae699ef45d918a037961c"
name = "embedded-app-boilerplate"
handle = "embedded-app-boilerplate-1"
application_url = "https://embedded-app.ngrok.dev/"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [ "https://embedded-app.ngrok.dev/api/auth/callback" ]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false