# Learn more about configuring your app at https://shopify.dev/docs/apps/build/cli-for-apps/app-configuration

client_id = ""
name = "embedded-app-boilerplate"
handle = "embedded-app-boilerplate-1"
application_url = "https://embedded-app.ngrok.dev/"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/api/usage/access-scopes
scopes = "read_themes"

[auth]
redirect_urls = [ "https://embedded-app.ngrok.dev/api/auth/callback" ]

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
# Learn more at https://shopify.dev/docs/api/admin-graphql/2025-01/enums/webhooksubscriptiontopic
topics=["app/uninstalled"]
uri = "/api/webhooks"
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false